### ISSUE TITLE
Stuck with compile error

### ISSUE THREAD

**Issue by leostardev** [tiagosiebler/okx-api#21]
Hi, Greetings! When I install okx-api in my react project and try to import and use it, It is stuck with error compiled with problems.
![image](https://user-images.githubusercontent.com/85182227/232817483-0d8ad1eb-8f8b-4809-a9b0-f4e48fd545ca.png)
Could you please help me with this issue?
Best regards.

**Comment by tiagosiebler** [comment]
Hey @leostardev - added some guidance in the readme:
https://github.com/tiagosiebler/okx-api#browserfrontend-usage

This is based on comments by another user in my bybit SDK: https://github.com/tiagosiebler/bybit-api/issues/258#issue-1703788230
