### ISSUE TITLE
seems that import { EventEmitter } from 'events'; is not supported in browser

### ISSUE THREAD

**Issue by hsuehic** [tiagosiebler/okx-api#31]
seems that import { EventEmitter } from 'events'; is not supported in browser

**Comment by tiagosiebler** [comment]
Unfortunately not, I'm looking to improve that in future but need to research more. In the meantime, if you're using typescript, there's an easy way you can provide polyfills via your tsconfig:
https://github.com/tiagosiebler/okx-api#browserfrontend-usage

**Comment by hsuehic** [comment]
Thanks for explanation. My issue was resolved.
