### ISSUE TITLE
Rest client submitOrder/getPositions instType

### ISSUE THREAD

**Issue by pegaltier** [tiagosiebler/okx-api#35]
I'm trying to use the Rest client but I see two issues so far:
- client.submitOrder({...}) ==> works well but the order is executed on the SPOT market, how can i choose FUTURES instead?
- client.getPositions({ instType: 'SPOT' }) ==> ERROR: {"code":"51000","data":[],"msg":"Parameter instType error"}.

**Comment by tiagosiebler** [comment]
Hi @pegaltier , I believe "positions" are a concept that exchanges typically don't associate with spot trading, you would need to track your own cost averages/positions while trading on spot markets. You can see in the api docs that "spot" is not a supported instType for this method:
https://www.okx.com/docs-v5/en/#trading-account-rest-api-get-positions

Regarding futures, you would need to set the `tdMode` parameter. Spot markets are when submitting a market order with `tdMode: 'cash'`
