### ISSUE TITLE
Running for 3-4 minutes will result in：'Pong timeout - closing socket to reconnect'

### ISSUE THREAD

**Issue by tingshuai** [tiagosiebler/okx-api#81]
**oxk-api version:^1.4.10;**
**node v20.10.0**
as image show:

![屏幕截图 2024-11-18 221837](https://github.com/user-attachments/assets/c878acd5-8d5f-4fa3-8927-9329f0d36276)

**Comment by tiagosiebler** [comment]
Hi @tingshuai - can you reproduce this with simple code like this: https://gist.github.com/tiagosiebler/113c7dec34f75603254cff990f36849b

I've tried to force a pong timeout to see if the reconnection logic has any issues, and I don't see any problems:
<img width="918" alt="Screenshot 2024-11-18 at 14 31 24" src="https://github.com/user-attachments/assets/49688482-744d-4dc7-a4da-5f1b89426560">

It recovers successfully and re-subscribes as expected. It's possible that the typeerror is thrown by your code somewhere in your event handler (your callstack within the event handler). Either way, if you can show me how to reproduce it with a simple scenario, I can try to help futher.

**Comment by tingshuai** [comment]
> can you reproduce this with simple code like this:

**I tested the same minimal code that fits my environment on both CodeSandbox and my local machine and found:**

1. On CodeSandbox, reconnection occurs, but it doesn't show the message 'Pong timeout - closing socket to reconnect,' and it takes a longer time for the reconnection issue to arise.
2. On the local machine, the time it takes for this issue to occur is uncertain; it could be a few minutes, several minutes, or even an hour.
3. On my local machine, I'm using Windows 11 with Node.js version v20.10.0.
4. This is the example on [CodeSandbox](https://codesandbox.io/p/devbox/m9p5dc), and this is the [code repository](https://github.com/tingshuai/testnest) I ran on my local machine; the code is identical.

**Comment by tiagosiebler** [comment]
Reconnects are normal and can happen. It's more of an issue if:
- they are happening constantly / too frequently (most likely a network issue on your end)
- they don't reconnect successfully (unexpected errors / stack traces, failure to reconnect/resubscribe properly, etc).

That being said, I've tried to force a situation where the reconnection is happening more frequently and I see no issues with your nestjs project either. Each time it triggers a reconnect, it seems to:
- properly clean up the "dead" connection
- emit a "reconnect" event to let you know what's happening
- successfully reconnect a new connection
- emit a "reconnected" event to let you know it reconnected
- successfully resubscribes to the topics you were subscribed to

You can see the workflow in the logs, especially after enabling the "silly" trace logger level:
<img width="1531" alt="Screenshot 2024-11-21 at 10 48 56" src="https://github.com/user-attachments/assets/b6ac6c23-09f3-49b3-b178-5f234b4c320c">

This seems to be working as expected - I don't see a stack trace like you've showed me...

**Comment by tingshuai** [comment]
> This seems to be working as expected - I don't see a stack trace like you've showed me...

Alright,thank you

**Comment by tiagosiebler** [comment]
No problem, if you notice anything else with the SDK you're not sure about, let me know!
