### ISSUE TITLE
How to handle failed websocket authentication?

### ISSUE THREAD

**Issue by LeThanh-dev** [tiagosiebler/okx-api#83]
i subcribe ws socket order privste but when password acc not true it ws reconnect auto. how can i turn off auto reconnect ?

**Comment by tiagosiebler** [comment]
You could handle the exception in the "error" event:
```
const wsClient = new WebsocketClient(
  {
    accounts: [
      {
        apiKey: 'INCORRECT_API_KEY',
        apiSecret: 'INCORRECT_API_SECRET',
        apiPass: 'INCORRECT_API_PASSPHRASE',
      },
    ],
  }
);

wsClient.on('error', (data) => {
  console.error('ws exception: ', data);

  const INVALID_API_KEY_ERROR = '60005';
  if (data.event === 'error' && data.code === INVALID_API_KEY_ERROR) {
    console.error(`Detected auth failure - closing websocket`);
    wsClient.close(data.wsKey);
  }
});
```

The "wsKey" identifies the connection. This way you can ask the WS client to close that connection - no more reconnects.

You could also try to make a test api call (e.g. fetching account balance) before trying to open a private WS connection, so you don't have this scenario.

**Comment by tiagosiebler** [comment]
Small demo here: https://github.com/tiagosiebler/okx-api/blob/master/examples/ws-private-handle-auth-fail.ts#L51-L55

but as I said, I definitely recommend you check credentials via a REST API call first before attempting a connection. Otherwise, the on->error event is a good place to handle this.
